accounts/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    # other paths
    path('logout/',views.logout, name='logout'),
    path('dashboard/',views.dashboard, name='dashboard'),
    # path('',views.dashboard, name='dashboard'),
    path('forgotPassword/',views.forgotPassword, name='forgotPassword'),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/',views.resetPassword, name='resetPassword'),
]

carts/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

nishabd/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Users must have an email address")
        if not username:
            raise ValueError("Users must have a username")
        
        # Check if the username already exists
        if self.model.objects.filter(username=username).exists():
            raise ValueError("A user with that username already exists")


        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password, **extra_fields):
        extra_fields.setdefault("is_admin", True)
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_superadmin", True)
        extra_fields.setdefault("user_type", "admin")

        if extra_fields.get("is_admin") is not True:
            raise ValueError("Superuser must have is_admin=True")

        return self.create_user(first_name, last_name, username, email, password, **extra_fields)

class Account(AbstractBaseUser):
    USER_TYPES = (
        ("consumer", "Consumer"),
        ("producer", "Producer"),
        ("admin", "Admin"),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)
    user_type = models.CharField(max_length=10, choices=USER_TYPES, default="consumer")

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from .models import Account
from django.contrib.auth.decorators import login_required

# verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

# Create your views here.

from carts.views import _cart_id
from carts.models import Cart,CartItem
import requests

def register(request):
    if request.method == 'POST':
        user_type = request.POST.get('user_type')

        if user_type == 'consumer':
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            email = request.POST.get('email')
            phone_number = request.POST.get('phone_number')
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')

        elif user_type == 'producer':
            first_name = request.POST.get('first_name_producer')
            last_name = request.POST.get('last_name_producer')
            email = request.POST.get('email_producer')
            phone_number = request.POST.get('phone_number_producer')
            password = request.POST.get('password_producer')
            confirm_password = request.POST.get('confirm_password_producer')

        else:
            messages.error(request, 'Invalid user type selected.')
            return redirect('register')

        if password != confirm_password:
            messages.error(request, 'Passwords do not match.')
            return redirect('register')

        try:
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=email,  # Set username as email for simplicity
                password=password,
                user_type=user_type,
                phone_number=phone_number,
            )

            user.save()

            # user ACTIVATION
            current_site = get_current_site(request)
            mail_subject = 'Please activate your Account'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid' : urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            # messages.success(request, 'Registration successful. Please log in.')
            return redirect('/accounts/login/?command=verification&email='+email)
        
        except Exception as e:
            messages.error(request, f'Error: {e}')
            return redirect('register')

    return render(request, 'accounts/register.html')

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id= _cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)
                    
                    # getting the product variation by cart id
                    product_variation = []
                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # get the cart items from the users to access his product variation
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id = item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item= CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass
            auth.login(request, user)
            messages.success(request, 'You are now Logged in')
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('dashboard')
        else:
            messages.error(request, 'Invalid Login Credentials')
            return redirect('login')
    return render(request, 'accounts/login.html')

@login_required(login_url = 'login')
def logout(request):
    auth.logout(request)
    messages.success(request, 'You are logged Out!')
    return redirect('login')

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError,ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your Account is activated.')
        return redirect('login')
    else:
        messages.error(request, 'Invalid Activation Link')
        return redirect('register')

@login_required(login_url = 'login')     
def dashboard(request):
    return render(request, 'accounts/dashboard.html')

def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__iexact=email)

            # reset password mail
            current_site = get_current_site(request)
            mail_subject = 'Reset Your Password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid' : urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('login')
        else:
            messages.error(request, 'Account Does Not Exists.')
            return redirect('forgotPassword')
    return render(request,'accounts/forgotPassword.html')

def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError,ValueError, OverflowError, Account.DoesNotExist):
        user = None
    
    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your Password.')
        return redirect('resetPassword')
    else:
        messages.error(request, 'This link has been expired.')
        return redirect('login')
def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful.')
            return redirect('login')

        else:
            messages.error(request, 'Password Do not match!')
            return redirect('resetPassword')
        
    else:
        return render(request, 'accounts/resetPassword.html')

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{ user.first_name }},

Please click on below link to confirm your registration.
http://{{domain}}{% url 'activate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

templates/accounts/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<section class="section-conten padding-y bg">
    {% include "includes/alerts.html" %}

    <div class="container">
        <div class="row">
        <aside class="col-md-3">
            <!--   SIDEBAR   -->
            <ul class="list-group">
                <a class="list-group-item active" href="#"> My order history </a>
                <a class="list-group-item" href="#"> Transactions </a>
                <a class="list-group-item" href="#"> Return and refunds </a>
                <a class="list-group-item" href="#">Settings </a>
                <a class="list-group-item" href="#"> My Selling Items </a>
                <a class="list-group-item" href="#"> Received orders </a>
            </ul>
            <br>
            <a class="btn btn-light btn-block" href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
            <!--   SIDEBAR .//END   -->
        </aside>
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
                <span>Order Date: 16 December 2018</span>
            </header>
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-8">
                        <h6 class="text-muted">Delivery to</h6>
                        <p>Michael Jackson <br>  
                        Phone +1234567890 Email: myname@pixsellz.com <br>
                        Location: Home number, Building name, Street 123,  Tashkent, UZB <br> 
                        P.O. Box: 100123
                         </p>
                    </div>
                    <div class="col-md-4">
                        <h6 class="text-muted">Payment</h6>
                        <span class="text-success">
                            <i class="fab fa-lg fa-cc-visa"></i>
                            Visa  **** 4216  
                        </span>
                        <p>Subtotal: $356 <br>
                         Shipping fee:  $56 <br> 
                         <span class="b">Total:  $456 </span>
                        </p>
                    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            <div class="table-responsive">
            <table class="table table-hover">
                <tr>
                    <td width="65">
                        <img src="{% static '/images/items/1.jpg' %}" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">Product name goes here </p>
                        <var class="price text-muted">USD 145</var>
                    </td>
                    <td> Seller <br> Nike clothing </td>
                    <td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
                <tr>
                    <td>
                        <img src="{% static '/images/items/2.jpg' %}" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">Another name goes here </p>
                        <var class="price text-muted">USD 15</var>
                    </td>
                    <td> Seller <br> ABC shop </td>
                    <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
                <tr>
                    <td>
                        <img src="{% static '/images/items/3.jpg' %}" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">The name of the product  goes here </p>
                        <var class="price text-muted">USD 145</var>
                    </td>
                    <td> Seller <br> Wallmart </td>
                    <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
            </table>
            </div> <!-- table-responsive .end// -->
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>

{% endblock %}

templates/accounts/forgotPassword.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

    
    <div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
            
          <div class="card-body">
          <h4 class="card-title mb-4">Forgot Password</h4>
          {% include "includes/alerts.html" %}
          <form action="{% url 'forgotPassword' %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email">
              </div> <!-- form-group// -->
              
              
              <div class="form-group">
                  <a href="{% url 'login' %}" class="float-right">Got Password? Login</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    

    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}">

</head>
<body>
    <div class="form-container">
        {% if request.GET.command == 'verification' %} 

    <div class="container mx-auto alert alert-info text-center" role='alert' style="max-width: 1024px; margin-top:100px;">
    Thanks, We have sent you an email for Account Activation to [{{ request.GET.email }}].
    <br><br>
    Already Verified? <a href="{% url 'login' %}">Login</a>
    </div>

    {% else %}
        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            
            <h2>Login</h2>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>

            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>

            <div class="form-group">
                <a href="{% url 'forgotPassword' %}" class="float-right">Forgot password?</a> 
             
            </div> <!-- form-group form-check .// -->

            <button type="submit">Login</button>
        </form>
        <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    {% endif %}
    </div>
</body>
</html>

templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/register_style.css' %}">
    <title>Registration Page</title>
</head>
<body>

<div class="container">
    {% include "includes/alerts.html" %}
    <form id="registrationForm" action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <h2>Sign Up</h2>
        <h3>Would you like to continue as a</h3>
<div class="form-row">
    <div class="form-group radio-group">
        <input type="radio" id="consumer" name="user_type" value="consumer" required>
        <label for="consumer">Consumer</label>
    </div>
    <div class="form-group radio-group">
        <input type="radio" id="producer" name="user_type" value="producer" required>
        <label for="producer">Producer</label>
    </div>
</div>

        <div id="consumer-form" class="form-group" style="display:none;">
            <h2>Consumer Registration</h2>
            <div class="form-row">
                <div class="col form-group">
                    <label for="id_first_name">First name</label>
                    <input type="text" id="id_first_name" name="first_name" class="form-control">
                </div>
                <div class="col form-group">
                    <label for="id_last_name">Last name</label>
                    <input type="text" id="id_last_name" name="last_name" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_email">Email</label>
                    <input type="email" id="id_email" name="email" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_phone_number">Phone Number</label>
                    <input type="text" id="id_phone_number" name="phone_number" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_password">Create password</label>
                    <input type="password" id="id_password" name="password" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_confirm_password">Repeat password</label>
                    <input type="password" id="id_confirm_password" name="confirm_password" class="form-control">
                </div>
            </div>
        </div>

        <div id="producer-form" class="form-group" style="display:none;">
            <h2>Producer Registration</h2>
            <div class="form-row">
                <div class="col form-group">
                    <label for="id_first_name_producer">First name</label>
                    <input type="text" id="id_first_name_producer" name="first_name_producer" class="form-control">
                </div>
                <div class="col form-group">
                    <label for="id_last_name_producer">Last name</label>
                    <input type="text" id="id_last_name_producer" name="last_name_producer" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_email_producer">Email</label>
                    <input type="email" id="id_email_producer" name="email_producer" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_phone_number_producer">Phone Number</label>
                    <input type="text" id="id_phone_number_producer" name="phone_number_producer" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_password_producer">Create password</label>
                    <input type="password" id="id_password_producer" name="password_producer" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_confirm_password_producer">Repeat password</label>
                    <input type="password" id="id_confirm_password_producer" name="confirm_password_producer" class="form-control">
                </div>
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Register </button>
        </div>
    </form>
    <p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p>
        <br><br>
</div>

<script>
    document.getElementById('consumer').addEventListener('click', function() {
        document.getElementById('consumer-form').style.display = 'block';
        document.getElementById('producer-form').style.display = 'none';
        updateFormRequirements('consumer-form', true);
        updateFormRequirements('producer-form', false);
    });

    document.getElementById('producer').addEventListener('click', function() {
        document.getElementById('consumer-form').style.display = 'none';
        document.getElementById('producer-form').style.display = 'block';
        updateFormRequirements('consumer-form', false);
        updateFormRequirements('producer-form', true);
    });

    function updateFormRequirements(formId, required) {
        var inputs = document.querySelectorAll('#' + formId + ' input');
        for (var i = 0; i < inputs.length; i++) {
            inputs[i].required = required;
        }
    }
</script>

</body>
</html>

templates/accounts/resetPassword.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

    
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            
          <div class="card-body">
          <h4 class="card-title mb-4">Reset Password</h4>
          {% include "includes/alerts.html" %}
          <form action="{% url 'resetPassword' %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                <input type="password" class="form-control" placeholder=" Create Password" name="password">
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password">
              </div> <!-- form-group// -->
              

              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Reset  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}  

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{ user.first_name }},

As requested, please click below link to reset your password. 
http://{{domain}}{% url 'resetpassword_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}